In [1]:
import polars as pr

In [2]:
path = r"C:\BA_Data\tiktok_de_2025_harmonized.parquet"
path2 = r"C:\BA_Data\tiktok_de_2025.parquet"

In [3]:
last_5 = (
    pr.scan_parquet(path)
    .tail(5)
    .collect()
)

last_6 = (
    pr.scan_parquet(path2)
    .tail(5)
    .collect()
)

In [4]:
last_5

shape: (5, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ uuid      ┆ content_t ┆ automated ┆ automated ┆ … ┆ category_ ┆ applicati ┆ category_ ┆ applicat │
│ ---       ┆ ype       ┆ _detectio ┆ _decision ┆   ┆ raw       ┆ on_date_r ┆ harmonize ┆ ion_date │
│ str       ┆ ---       ┆ n         ┆ ---       ┆   ┆ ---       ┆ aw        ┆ d         ┆ _harmoni │
│           ┆ str       ┆ ---       ┆ str       ┆   ┆ str       ┆ ---       ┆ ---       ┆ zed      │
│           ┆           ┆ str       ┆           ┆   ┆           ┆ date      ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ date     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 4792b3a4- ┆ ["CONTENT ┆ Yes       ┆ AUTOMATED ┆ … ┆ STATEMENT ┆ 2025-10-0 ┆ PROTECTIO ┆ 2025-10- │
│ 8b6f-432f ┆ _TYPE_IMA ┆           ┆ _DECISION ┆   ┆ _CATEGORY ┆ 2         ┆ N_OF_MINO ┆ 02       │
│ -8fd3-abd ┆ GE"]      ┆           ┆ _NOT_AUTO ┆   ┆ _PROTECTI ┆           ┆ RS        ┆          │
│ 909…      ┆           ┆           ┆ MAT…      ┆   ┆ ON_…      ┆           ┆           ┆          │
│ fc2c459b- ┆ ["CONTENT ┆ Yes       ┆ AUTOMATED ┆ … ┆ STATEMENT ┆ 2025-10-0 ┆ PROTECTIO ┆ 2025-10- │
│ 20df-459f ┆ _TYPE_TEX ┆           ┆ _DECISION ┆   ┆ _CATEGORY ┆ 2         ┆ N_OF_MINO ┆ 02       │
│ -8dfc-518 ┆ T"]       ┆           ┆ _FULLY    ┆   ┆ _PROTECTI ┆           ┆ RS        ┆          │
│ e46…      ┆           ┆           ┆           ┆   ┆ ON_…      ┆           ┆           ┆          │
│ 2586a0cd- ┆ ["CONTENT ┆ Yes       ┆ AUTOMATED ┆ … ┆ STATEMENT ┆ 2025-10-0 ┆ PROTECTIO ┆ 2025-10- │
│ d2ed-41d5 ┆ _TYPE_IMA ┆           ┆ _DECISION ┆   ┆ _CATEGORY ┆ 2         ┆ N_OF_MINO ┆ 02       │
│ -9b47-f87 ┆ GE"]      ┆           ┆ _NOT_AUTO ┆   ┆ _PROTECTI ┆           ┆ RS        ┆          │
│ ed8…      ┆           ┆           ┆ MAT…      ┆   ┆ ON_…      ┆           ┆           ┆          │
│ 985f7b7a- ┆ ["CONTENT ┆ Yes       ┆ AUTOMATED ┆ … ┆ STATEMENT ┆ 2025-10-0 ┆ PROTECTIO ┆ 2025-10- │
│ 0d3a-46d3 ┆ _TYPE_IMA ┆           ┆ _DECISION ┆   ┆ _CATEGORY ┆ 2         ┆ N_OF_MINO ┆ 02       │
│ -9bc2-02e ┆ GE"]      ┆           ┆ _NOT_AUTO ┆   ┆ _PROTECTI ┆           ┆ RS        ┆          │
│ 565…      ┆           ┆           ┆ MAT…      ┆   ┆ ON_…      ┆           ┆           ┆          │
│ 2b3a9d9f- ┆ ["CONTENT ┆ Yes       ┆ AUTOMATED ┆ … ┆ STATEMENT ┆ 2025-10-0 ┆ PROTECTIO ┆ 2025-10- │
│ 826c-4a78 ┆ _TYPE_VID ┆           ┆ _DECISION ┆   ┆ _CATEGORY ┆ 2         ┆ N_OF_MINO ┆ 02       │
│ -bea2-581 ┆ EO"]      ┆           ┆ _NOT_AUTO ┆   ┆ _PROTECTI ┆           ┆ RS        ┆          │
│ 20e…      ┆           ┆           ┆ MAT…      ┆   ┆ ON_…      ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
last_6

shape: (5, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ uuid      ┆ category  ┆ content_t ┆ automated ┆ … ┆ applicati ┆ platform_ ┆ decision_ ┆ api_vers │
│ ---       ┆ ---       ┆ ype       ┆ _detectio ┆   ┆ on_date   ┆ name      ┆ visibilit ┆ ion      │
│ str       ┆ str       ┆ ---       ┆ n         ┆   ┆ ---       ┆ ---       ┆ y         ┆ ---      │
│           ┆           ┆ str       ┆ ---       ┆   ┆ datetime[ ┆ str       ┆ ---       ┆ str      │
│           ┆           ┆           ┆ str       ┆   ┆ ms]       ┆           ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 85c0103d- ┆ STATEMENT ┆ ["CONTENT ┆ Yes       ┆ … ┆ 2025-12-1 ┆ TikTok    ┆ ["DECISIO ┆ v2       │
│ 5f58-43d6 ┆ _CATEGORY ┆ _TYPE_TEX ┆           ┆   ┆ 2         ┆           ┆ N_VISIBIL ┆          │
│ -9a72-2ec ┆ _SCAMS_AN ┆ T"]       ┆           ┆   ┆ 00:00:00  ┆           ┆ ITY_CONTE ┆          │
│ 86a…      ┆ D_F…      ┆           ┆           ┆   ┆           ┆           ┆ NT_…      ┆          │
│ 2e580d7e- ┆ STATEMENT ┆ ["CONTENT ┆ Yes       ┆ … ┆ 2025-12-1 ┆ TikTok    ┆ ["DECISIO ┆ v2       │
│ 221e-4d20 ┆ _CATEGORY ┆ _TYPE_TEX ┆           ┆   ┆ 2         ┆           ┆ N_VISIBIL ┆          │
│ -b244-422 ┆ _ILLEGAL_ ┆ T"]       ┆           ┆   ┆ 00:00:00  ┆           ┆ ITY_CONTE ┆          │
│ 34d…      ┆ OR_…      ┆           ┆           ┆   ┆           ┆           ┆ NT_…      ┆          │
│ 89a1d513- ┆ STATEMENT ┆ ["CONTENT ┆ Yes       ┆ … ┆ 2025-12-1 ┆ TikTok    ┆ ["DECISIO ┆ v2       │
│ bebe-4629 ┆ _CATEGORY ┆ _TYPE_VID ┆           ┆   ┆ 2         ┆           ┆ N_VISIBIL ┆          │
│ -9cdd-088 ┆ _OTHER_VI ┆ EO"]      ┆           ┆   ┆ 00:00:00  ┆           ┆ ITY_OTHER ┆          │
│ 25b…      ┆ OLA…      ┆           ┆           ┆   ┆           ┆           ┆ "]        ┆          │
│ 36e88d3a- ┆ STATEMENT ┆ ["CONTENT ┆ Yes       ┆ … ┆ 2025-12-1 ┆ TikTok    ┆ ["DECISIO ┆ v2       │
│ cefd-449a ┆ _CATEGORY ┆ _TYPE_TEX ┆           ┆   ┆ 2         ┆           ┆ N_VISIBIL ┆          │
│ -8950-e5e ┆ _ILLEGAL_ ┆ T"]       ┆           ┆   ┆ 00:00:00  ┆           ┆ ITY_CONTE ┆          │
│ 822…      ┆ OR_…      ┆           ┆           ┆   ┆           ┆           ┆ NT_…      ┆          │
│ c289eab6- ┆ STATEMENT ┆ ["CONTENT ┆ Yes       ┆ … ┆ 2025-12-1 ┆ TikTok    ┆ ["DECISIO ┆ v2       │
│ 14a6-448b ┆ _CATEGORY ┆ _TYPE_VID ┆           ┆   ┆ 2         ┆           ┆ N_VISIBIL ┆          │
│ -8a2d-4db ┆ _OTHER_VI ┆ EO"]      ┆           ┆   ┆ 00:00:00  ┆           ┆ ITY_OTHER ┆          │
│ c5a…      ┆ OLA…      ┆           ┆           ┆   ┆           ┆           ┆ "]        ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘